// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: meshapi/gateway/codegen/gateway.proto

package codegen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGatewayConfigFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// proto_file is the proto file that is currently being processed.
	ProtoFile *descriptorpb.FileDescriptorProto `protobuf:"bytes,1,opt,name=proto_file,json=protoFile,proto3" json:"proto_file,omitempty"`
}

func (x *GetGatewayConfigFileRequest) Reset() {
	*x = GetGatewayConfigFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_codegen_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGatewayConfigFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigFileRequest) ProtoMessage() {}

func (x *GetGatewayConfigFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_codegen_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigFileRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigFileRequest) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_codegen_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetGatewayConfigFileRequest) GetProtoFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.ProtoFile
	}
	return nil
}

type GetGatewayConfigFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// file_path is the path to the config file that contains the gateway endpoints.
	//
	// yaml, yml and json extension will be tried for this file and if the path is relative, it will be
	// from the search path.
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *GetGatewayConfigFileResponse) Reset() {
	*x = GetGatewayConfigFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_codegen_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGatewayConfigFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayConfigFileResponse) ProtoMessage() {}

func (x *GetGatewayConfigFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_codegen_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayConfigFileResponse.ProtoReflect.Descriptor instead.
func (*GetGatewayConfigFileResponse) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_codegen_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetGatewayConfigFileResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_meshapi_gateway_codegen_gateway_proto protoreflect.FileDescriptor

var file_meshapi_gateway_codegen_gateway_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x62, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x43, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x3b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x32, 0x99, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x74, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x83, 0x01, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x34, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x67, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x67,
	0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x72, 0x65, 0x73, 0x74, 0x2d,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x64, 0x65,
	0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshapi_gateway_codegen_gateway_proto_rawDescOnce sync.Once
	file_meshapi_gateway_codegen_gateway_proto_rawDescData = file_meshapi_gateway_codegen_gateway_proto_rawDesc
)

func file_meshapi_gateway_codegen_gateway_proto_rawDescGZIP() []byte {
	file_meshapi_gateway_codegen_gateway_proto_rawDescOnce.Do(func() {
		file_meshapi_gateway_codegen_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshapi_gateway_codegen_gateway_proto_rawDescData)
	})
	return file_meshapi_gateway_codegen_gateway_proto_rawDescData
}

var file_meshapi_gateway_codegen_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshapi_gateway_codegen_gateway_proto_goTypes = []interface{}{
	(*GetGatewayConfigFileRequest)(nil),      // 0: meshapi.gateway.codegen.GetGatewayConfigFileRequest
	(*GetGatewayConfigFileResponse)(nil),     // 1: meshapi.gateway.codegen.GetGatewayConfigFileResponse
	(*descriptorpb.FileDescriptorProto)(nil), // 2: google.protobuf.FileDescriptorProto
}
var file_meshapi_gateway_codegen_gateway_proto_depIdxs = []int32{
	2, // 0: meshapi.gateway.codegen.GetGatewayConfigFileRequest.proto_file:type_name -> google.protobuf.FileDescriptorProto
	0, // 1: meshapi.gateway.codegen.RestGatewayPlugin.GetGatewayConfigFile:input_type -> meshapi.gateway.codegen.GetGatewayConfigFileRequest
	1, // 2: meshapi.gateway.codegen.RestGatewayPlugin.GetGatewayConfigFile:output_type -> meshapi.gateway.codegen.GetGatewayConfigFileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meshapi_gateway_codegen_gateway_proto_init() }
func file_meshapi_gateway_codegen_gateway_proto_init() {
	if File_meshapi_gateway_codegen_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshapi_gateway_codegen_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGatewayConfigFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_codegen_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGatewayConfigFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshapi_gateway_codegen_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshapi_gateway_codegen_gateway_proto_goTypes,
		DependencyIndexes: file_meshapi_gateway_codegen_gateway_proto_depIdxs,
		MessageInfos:      file_meshapi_gateway_codegen_gateway_proto_msgTypes,
	}.Build()
	File_meshapi_gateway_codegen_gateway_proto = out.File
	file_meshapi_gateway_codegen_gateway_proto_rawDesc = nil
	file_meshapi_gateway_codegen_gateway_proto_goTypes = nil
	file_meshapi_gateway_codegen_gateway_proto_depIdxs = nil
}
