// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: meshapi/gateway/codegen/gateway.proto

package codegen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestGatewayPluginClient is the client API for RestGatewayPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestGatewayPluginClient interface {
	GetGatewayConfigFile(ctx context.Context, in *GetGatewayConfigFileRequest, opts ...grpc.CallOption) (*GetGatewayConfigFileResponse, error)
}

type restGatewayPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewRestGatewayPluginClient(cc grpc.ClientConnInterface) RestGatewayPluginClient {
	return &restGatewayPluginClient{cc}
}

func (c *restGatewayPluginClient) GetGatewayConfigFile(ctx context.Context, in *GetGatewayConfigFileRequest, opts ...grpc.CallOption) (*GetGatewayConfigFileResponse, error) {
	out := new(GetGatewayConfigFileResponse)
	err := c.cc.Invoke(ctx, "/meshapi.gateway.codegen.RestGatewayPlugin/GetGatewayConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestGatewayPluginServer is the server API for RestGatewayPlugin service.
// All implementations must embed UnimplementedRestGatewayPluginServer
// for forward compatibility
type RestGatewayPluginServer interface {
	GetGatewayConfigFile(context.Context, *GetGatewayConfigFileRequest) (*GetGatewayConfigFileResponse, error)
	mustEmbedUnimplementedRestGatewayPluginServer()
}

// UnimplementedRestGatewayPluginServer must be embedded to have forward compatible implementations.
type UnimplementedRestGatewayPluginServer struct {
}

func (UnimplementedRestGatewayPluginServer) GetGatewayConfigFile(context.Context, *GetGatewayConfigFileRequest) (*GetGatewayConfigFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayConfigFile not implemented")
}
func (UnimplementedRestGatewayPluginServer) mustEmbedUnimplementedRestGatewayPluginServer() {}

// UnsafeRestGatewayPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestGatewayPluginServer will
// result in compilation errors.
type UnsafeRestGatewayPluginServer interface {
	mustEmbedUnimplementedRestGatewayPluginServer()
}

func RegisterRestGatewayPluginServer(s grpc.ServiceRegistrar, srv RestGatewayPluginServer) {
	s.RegisterService(&RestGatewayPlugin_ServiceDesc, srv)
}

func _RestGatewayPlugin_GetGatewayConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayConfigFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestGatewayPluginServer).GetGatewayConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshapi.gateway.codegen.RestGatewayPlugin/GetGatewayConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestGatewayPluginServer).GetGatewayConfigFile(ctx, req.(*GetGatewayConfigFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestGatewayPlugin_ServiceDesc is the grpc.ServiceDesc for RestGatewayPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestGatewayPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meshapi.gateway.codegen.RestGatewayPlugin",
	HandlerType: (*RestGatewayPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayConfigFile",
			Handler:    _RestGatewayPlugin_GetGatewayConfigFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meshapi/gateway/codegen/gateway.proto",
}
