# yaml-language-server: $schema=/home/peyman/projects/meshapi/grpc-api-gateway/api/Config.schema.json
openapi:
  document:
    info:
      title: Integration Test API
      summary: This is an API only to demonstrate capabilities of gRPC Gateway and Open API generation.
      description: |
        Description of the OpenAPI would go here.
      version: v0.1
