// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: meshapi/gateway/config.proto

package api

import (
	openapi "github.com/meshapi/grpc-api-gateway/api/openapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenAPIServiceSpec defines configuration for generating OpenAPI documentation for gRPC services.
type OpenAPIServiceSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// selector is a dot-separated gRPC service method selector.
	//
	// If the selector begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyService`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	//
	// If the selector does not begin with '~.', it will be treated as a fully qualified method name (FQMN).
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// document can be used to override default values for OpenAPI document files when using the option to generate
	// OpenAPI files per service.
	//
	// Additionally, this can be used to change documentation generation behavior such as default responses regardless
	// of the output generation mode.
	//
	// NOTE: This document will only be used when using output mode of "service" and in all other
	// modes, this object simply gets ignored save for the config field. Since the config field instructs
	// the generation of responses and the document objects for that service only, regardless of the output mode
	// the settings will be honored.
	Document *openapi.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	// methods maps each method to an operation configuration.
	Methods map[string]*openapi.Operation `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OpenAPIServiceSpec) Reset() {
	*x = OpenAPIServiceSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAPIServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIServiceSpec) ProtoMessage() {}

func (x *OpenAPIServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIServiceSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIServiceSpec) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_config_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAPIServiceSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIServiceSpec) GetDocument() *openapi.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *OpenAPIServiceSpec) GetMethods() map[string]*openapi.Operation {
	if x != nil {
		return x.Methods
	}
	return nil
}

// OpenAPIMessageSpec defines configuration for generating OpenAPI documentation for protobuf messages.
type OpenAPIMessageSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// selector is a dot-separated protobuf message selector.
	//
	// If the selector begins with a '.', it will be treated as an absolute path.
	// If it begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyMessage`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	// If the path does not begin with a '.' or '~.', it will be treated as a relative path and a search
	// from the current proto package will be performed in order to find the message.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// schema controls the OpenAPI v3.1 schema generation for this proto message.
	Schema *openapi.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// fields allows controlling the OpenAPI v3.1 generation for individual fields in this proto message.
	Fields map[string]*openapi.Schema `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OpenAPIMessageSpec) Reset() {
	*x = OpenAPIMessageSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAPIMessageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIMessageSpec) ProtoMessage() {}

func (x *OpenAPIMessageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIMessageSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIMessageSpec) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_config_proto_rawDescGZIP(), []int{1}
}

func (x *OpenAPIMessageSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIMessageSpec) GetSchema() *openapi.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *OpenAPIMessageSpec) GetFields() map[string]*openapi.Schema {
	if x != nil {
		return x.Fields
	}
	return nil
}

// OpenAPIEnumSpec defines configuration for generating OpenAPI documentation for protobuf enums.
type OpenAPIEnumSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// selector is a dot-separated protobuf enum selector.
	//
	// If the selector begins with a '.', it will be treated as an absolute path.
	// If it begins with '~.', the current proto package will be added to the beginning
	// of the path. For instance: `~.MyEnum`. Since no proto package can be deduced in the global
	// config file, this alias cannot be used in the global config file.
	// If the path does not begin with a '.' or '~.', it will be treated as a relative path and a search
	// from the current proto package will be performed in order to find the enum.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// schema controls the OpenAPI v3.1 schema generation for this proto enum.
	Schema *openapi.Schema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *OpenAPIEnumSpec) Reset() {
	*x = OpenAPIEnumSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAPIEnumSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIEnumSpec) ProtoMessage() {}

func (x *OpenAPIEnumSpec) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIEnumSpec.ProtoReflect.Descriptor instead.
func (*OpenAPIEnumSpec) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_config_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAPIEnumSpec) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *OpenAPIEnumSpec) GetSchema() *openapi.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// OpenAPISpec defines the overall OpenAPI documentation configuration.
type OpenAPISpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Document is the OpenAPI v3.1 document configuration which controls how the OpenAPI documentation is generated.
	//
	// This document can be defined to define a base config for all documents (if in the global config) or the document
	// for the current output target. For instance, when using output mode of "service", each service defined in the
	// associated proto file inherits this base document and can additionally specify more defaults for its own OpenAPI
	// document. When defining this in the global config and for specific proto files, the configs get merged together
	// but the priority is given to the proto document.
	Document *openapi.Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// services is used to configure OpenAPI v3.1 output for gRPC services.
	Services []*OpenAPIServiceSpec `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	// messages is used to configure OpenAPI v3.1 output for protobuf messages.
	Messages []*OpenAPIMessageSpec `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// enums is used to configure OpenAPI v3.1 output for protobuf enums.
	Enums []*OpenAPIEnumSpec `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
}

func (x *OpenAPISpec) Reset() {
	*x = OpenAPISpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenAPISpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPISpec) ProtoMessage() {}

func (x *OpenAPISpec) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPISpec.ProtoReflect.Descriptor instead.
func (*OpenAPISpec) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_config_proto_rawDescGZIP(), []int{3}
}

func (x *OpenAPISpec) GetDocument() *openapi.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *OpenAPISpec) GetServices() []*OpenAPIServiceSpec {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *OpenAPISpec) GetMessages() []*OpenAPIMessageSpec {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OpenAPISpec) GetEnums() []*OpenAPIEnumSpec {
	if x != nil {
		return x.Enums
	}
	return nil
}

// Config is the content of a configuration file.
type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// gateway holds gateway configs.
	Gateway *GatewaySpec `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// openapi holds OpenAPI v3.1 configs.
	Openapi *OpenAPISpec `protobuf:"bytes,2,opt,name=openapi,proto3" json:"openapi,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_config_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetGateway() *GatewaySpec {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Config) GetOpenapi() *OpenAPISpec {
	if x != nil {
		return x.Openapi
	}
	return nil
}

var File_meshapi_gateway_config_proto protoreflect.FileDescriptor

var file_meshapi_gateway_config_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a,
	0x1d, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25,
	0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b, 0x02, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50,
	0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4a, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x1a, 0x5e, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x8e, 0x02, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12,
	0x47, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x5a, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x66, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x45,
	0x6e, 0x75, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x86, 0x02, 0x0a,
	0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x53, 0x70, 0x65, 0x63, 0x12, 0x3d, 0x0a, 0x08,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x36, 0x0a,
	0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x41, 0x50, 0x49, 0x45, 0x6e, 0x75, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05,
	0x65, 0x6e, 0x75, 0x6d, 0x73, 0x22, 0x78, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x36, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x36, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x50, 0x49, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_meshapi_gateway_config_proto_rawDescOnce sync.Once
	file_meshapi_gateway_config_proto_rawDescData = file_meshapi_gateway_config_proto_rawDesc
)

func file_meshapi_gateway_config_proto_rawDescGZIP() []byte {
	file_meshapi_gateway_config_proto_rawDescOnce.Do(func() {
		file_meshapi_gateway_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshapi_gateway_config_proto_rawDescData)
	})
	return file_meshapi_gateway_config_proto_rawDescData
}

var file_meshapi_gateway_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_meshapi_gateway_config_proto_goTypes = []interface{}{
	(*OpenAPIServiceSpec)(nil), // 0: meshapi.gateway.OpenAPIServiceSpec
	(*OpenAPIMessageSpec)(nil), // 1: meshapi.gateway.OpenAPIMessageSpec
	(*OpenAPIEnumSpec)(nil),    // 2: meshapi.gateway.OpenAPIEnumSpec
	(*OpenAPISpec)(nil),        // 3: meshapi.gateway.OpenAPISpec
	(*Config)(nil),             // 4: meshapi.gateway.Config
	nil,                        // 5: meshapi.gateway.OpenAPIServiceSpec.MethodsEntry
	nil,                        // 6: meshapi.gateway.OpenAPIMessageSpec.FieldsEntry
	(*openapi.Document)(nil),   // 7: meshapi.gateway.openapi.Document
	(*openapi.Schema)(nil),     // 8: meshapi.gateway.openapi.Schema
	(*GatewaySpec)(nil),        // 9: meshapi.gateway.GatewaySpec
	(*openapi.Operation)(nil),  // 10: meshapi.gateway.openapi.Operation
}
var file_meshapi_gateway_config_proto_depIdxs = []int32{
	7,  // 0: meshapi.gateway.OpenAPIServiceSpec.document:type_name -> meshapi.gateway.openapi.Document
	5,  // 1: meshapi.gateway.OpenAPIServiceSpec.methods:type_name -> meshapi.gateway.OpenAPIServiceSpec.MethodsEntry
	8,  // 2: meshapi.gateway.OpenAPIMessageSpec.schema:type_name -> meshapi.gateway.openapi.Schema
	6,  // 3: meshapi.gateway.OpenAPIMessageSpec.fields:type_name -> meshapi.gateway.OpenAPIMessageSpec.FieldsEntry
	8,  // 4: meshapi.gateway.OpenAPIEnumSpec.schema:type_name -> meshapi.gateway.openapi.Schema
	7,  // 5: meshapi.gateway.OpenAPISpec.document:type_name -> meshapi.gateway.openapi.Document
	0,  // 6: meshapi.gateway.OpenAPISpec.services:type_name -> meshapi.gateway.OpenAPIServiceSpec
	1,  // 7: meshapi.gateway.OpenAPISpec.messages:type_name -> meshapi.gateway.OpenAPIMessageSpec
	2,  // 8: meshapi.gateway.OpenAPISpec.enums:type_name -> meshapi.gateway.OpenAPIEnumSpec
	9,  // 9: meshapi.gateway.Config.gateway:type_name -> meshapi.gateway.GatewaySpec
	3,  // 10: meshapi.gateway.Config.openapi:type_name -> meshapi.gateway.OpenAPISpec
	10, // 11: meshapi.gateway.OpenAPIServiceSpec.MethodsEntry.value:type_name -> meshapi.gateway.openapi.Operation
	8,  // 12: meshapi.gateway.OpenAPIMessageSpec.FieldsEntry.value:type_name -> meshapi.gateway.openapi.Schema
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_meshapi_gateway_config_proto_init() }
func file_meshapi_gateway_config_proto_init() {
	if File_meshapi_gateway_config_proto != nil {
		return
	}
	file_meshapi_gateway_gateway_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_meshapi_gateway_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAPIServiceSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAPIMessageSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAPIEnumSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenAPISpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshapi_gateway_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshapi_gateway_config_proto_goTypes,
		DependencyIndexes: file_meshapi_gateway_config_proto_depIdxs,
		MessageInfos:      file_meshapi_gateway_config_proto_msgTypes,
	}.Build()
	File_meshapi_gateway_config_proto = out.File
	file_meshapi_gateway_config_proto_rawDesc = nil
	file_meshapi_gateway_config_proto_goTypes = nil
	file_meshapi_gateway_config_proto_depIdxs = nil
}
