// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: meshapi/gateway/gateway.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewaySpec holds gRPC gateway configurations.
type GatewaySpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// endpoints hold a series of endpoint binding specs.
	Endpoints []*EndpointBinding `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *GatewaySpec) Reset() {
	*x = GatewaySpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewaySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySpec) ProtoMessage() {}

func (x *GatewaySpec) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySpec.ProtoReflect.Descriptor instead.
func (*GatewaySpec) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewaySpec) GetEndpoints() []*EndpointBinding {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// EndpointBinding is a gRPC method - HTTP endpoint binding specification.
type EndpointBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// selector is dot separated gRPC service method selector.
	//
	// selector string can be configured to be relative if it begins with a '.' character
	// but this is only supported when using the proto generators and only if a package
	// can be deduced.
	//
	// if the selector does not begin with a '.' character, it will be treated as a
	// fully qualified method name (FQMN).
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Types that are assignable to Pattern:
	//
	//	*EndpointBinding_Get
	//	*EndpointBinding_Put
	//	*EndpointBinding_Post
	//	*EndpointBinding_Delete
	//	*EndpointBinding_Patch
	//	*EndpointBinding_Custom
	Pattern isEndpointBinding_Pattern `protobuf_oneof:"pattern"`
	// body is a request message field selector that will be read via HTTP body.
	//
	// value of '*' indicates that the entire request message gets decoded from the body.
	// default value of ” indicates that no part of the request gets decoded from the body.
	//
	// NOTE: Not all methods support HTTP body.
	Body string `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	// response_body is a response message field selector that will be written to HTTP response.
	//
	// default value of '*' or ” indicates that the entire response message gets encoded.
	ResponseBody string `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	// query_params are explicit query parameter bindings that can be used to rename
	// or ignore query parameters.
	QueryParams []*QueryParameterBinding `protobuf:"bytes,10,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	// additional_bindings holds additional bindings for the same gRPC service method.
	AdditionalBindings []*AdditionalEndpointBinding `protobuf:"bytes,11,rep,name=additional_bindings,json=additionalBindings,proto3" json:"additional_bindings,omitempty"`
	// disable_query_param_discovery can be used to avoid auto binding query parameters.
	DisableQueryParamDiscovery bool `protobuf:"varint,12,opt,name=disable_query_param_discovery,json=disableQueryParamDiscovery,proto3" json:"disable_query_param_discovery,omitempty"`
	// stream holds configurations for streaming methods.
	Stream *StreamConfig `protobuf:"bytes,13,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *EndpointBinding) Reset() {
	*x = EndpointBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointBinding) ProtoMessage() {}

func (x *EndpointBinding) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointBinding.ProtoReflect.Descriptor instead.
func (*EndpointBinding) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointBinding) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (m *EndpointBinding) GetPattern() isEndpointBinding_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (x *EndpointBinding) GetGet() string {
	if x, ok := x.GetPattern().(*EndpointBinding_Get); ok {
		return x.Get
	}
	return ""
}

func (x *EndpointBinding) GetPut() string {
	if x, ok := x.GetPattern().(*EndpointBinding_Put); ok {
		return x.Put
	}
	return ""
}

func (x *EndpointBinding) GetPost() string {
	if x, ok := x.GetPattern().(*EndpointBinding_Post); ok {
		return x.Post
	}
	return ""
}

func (x *EndpointBinding) GetDelete() string {
	if x, ok := x.GetPattern().(*EndpointBinding_Delete); ok {
		return x.Delete
	}
	return ""
}

func (x *EndpointBinding) GetPatch() string {
	if x, ok := x.GetPattern().(*EndpointBinding_Patch); ok {
		return x.Patch
	}
	return ""
}

func (x *EndpointBinding) GetCustom() *CustomPattern {
	if x, ok := x.GetPattern().(*EndpointBinding_Custom); ok {
		return x.Custom
	}
	return nil
}

func (x *EndpointBinding) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EndpointBinding) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *EndpointBinding) GetQueryParams() []*QueryParameterBinding {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *EndpointBinding) GetAdditionalBindings() []*AdditionalEndpointBinding {
	if x != nil {
		return x.AdditionalBindings
	}
	return nil
}

func (x *EndpointBinding) GetDisableQueryParamDiscovery() bool {
	if x != nil {
		return x.DisableQueryParamDiscovery
	}
	return false
}

func (x *EndpointBinding) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type isEndpointBinding_Pattern interface {
	isEndpointBinding_Pattern()
}

type EndpointBinding_Get struct {
	Get string `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type EndpointBinding_Put struct {
	Put string `protobuf:"bytes,3,opt,name=put,proto3,oneof"`
}

type EndpointBinding_Post struct {
	Post string `protobuf:"bytes,4,opt,name=post,proto3,oneof"`
}

type EndpointBinding_Delete struct {
	Delete string `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type EndpointBinding_Patch struct {
	Patch string `protobuf:"bytes,6,opt,name=patch,proto3,oneof"`
}

type EndpointBinding_Custom struct {
	// custom can be used for custom HTTP methods.
	Custom *CustomPattern `protobuf:"bytes,7,opt,name=custom,proto3,oneof"`
}

func (*EndpointBinding_Get) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Put) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Post) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Delete) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Patch) isEndpointBinding_Pattern() {}

func (*EndpointBinding_Custom) isEndpointBinding_Pattern() {}

type AdditionalEndpointBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Pattern:
	//
	//	*AdditionalEndpointBinding_Get
	//	*AdditionalEndpointBinding_Put
	//	*AdditionalEndpointBinding_Post
	//	*AdditionalEndpointBinding_Delete
	//	*AdditionalEndpointBinding_Patch
	//	*AdditionalEndpointBinding_Custom
	Pattern isAdditionalEndpointBinding_Pattern `protobuf_oneof:"pattern"`
	// body is a request message field selector that will be read via HTTP body.
	//
	// value of '*' indicates that the entire request message gets decoded from the body.
	// default value of ” indicates that no part of the request gets decoded from the body.
	//
	// NOTE: Not all methods support HTTP body.
	Body string `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	// response_body is a response message field selector that will be written to HTTP response.
	//
	// default value of '*' or ” indicates that the entire response message gets encoded.
	ResponseBody string `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	// query_params are explicit query parameter bindings that can be used to rename
	// or ignore query parameters.
	QueryParams []*QueryParameterBinding `protobuf:"bytes,10,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	// disable_query_param_discovery can be used to avoid auto binding query parameters.
	DisableQueryParamDiscovery bool `protobuf:"varint,11,opt,name=disable_query_param_discovery,json=disableQueryParamDiscovery,proto3" json:"disable_query_param_discovery,omitempty"`
	// stream holds configurations for streaming methods.
	Stream *StreamConfig `protobuf:"bytes,12,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *AdditionalEndpointBinding) Reset() {
	*x = AdditionalEndpointBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionalEndpointBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalEndpointBinding) ProtoMessage() {}

func (x *AdditionalEndpointBinding) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalEndpointBinding.ProtoReflect.Descriptor instead.
func (*AdditionalEndpointBinding) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (m *AdditionalEndpointBinding) GetPattern() isAdditionalEndpointBinding_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetGet() string {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Get); ok {
		return x.Get
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPut() string {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Put); ok {
		return x.Put
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPost() string {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Post); ok {
		return x.Post
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetDelete() string {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Delete); ok {
		return x.Delete
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetPatch() string {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Patch); ok {
		return x.Patch
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetCustom() *CustomPattern {
	if x, ok := x.GetPattern().(*AdditionalEndpointBinding_Custom); ok {
		return x.Custom
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *AdditionalEndpointBinding) GetQueryParams() []*QueryParameterBinding {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *AdditionalEndpointBinding) GetDisableQueryParamDiscovery() bool {
	if x != nil {
		return x.DisableQueryParamDiscovery
	}
	return false
}

func (x *AdditionalEndpointBinding) GetStream() *StreamConfig {
	if x != nil {
		return x.Stream
	}
	return nil
}

type isAdditionalEndpointBinding_Pattern interface {
	isAdditionalEndpointBinding_Pattern()
}

type AdditionalEndpointBinding_Get struct {
	Get string `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type AdditionalEndpointBinding_Put struct {
	Put string `protobuf:"bytes,3,opt,name=put,proto3,oneof"`
}

type AdditionalEndpointBinding_Post struct {
	Post string `protobuf:"bytes,4,opt,name=post,proto3,oneof"`
}

type AdditionalEndpointBinding_Delete struct {
	Delete string `protobuf:"bytes,5,opt,name=delete,proto3,oneof"`
}

type AdditionalEndpointBinding_Patch struct {
	Patch string `protobuf:"bytes,6,opt,name=patch,proto3,oneof"`
}

type AdditionalEndpointBinding_Custom struct {
	// custom can be used for custom HTTP methods.
	Custom *CustomPattern `protobuf:"bytes,7,opt,name=custom,proto3,oneof"`
}

func (*AdditionalEndpointBinding_Get) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Put) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Post) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Delete) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Patch) isAdditionalEndpointBinding_Pattern() {}

func (*AdditionalEndpointBinding_Custom) isAdditionalEndpointBinding_Pattern() {}

// CustomPattern describes an HTTP pattern and custom method.
type CustomPattern struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// method is the custom HTTP method.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// path is the HTTP path pattern.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CustomPattern) Reset() {
	*x = CustomPattern{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomPattern) ProtoMessage() {}

func (x *CustomPattern) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomPattern.ProtoReflect.Descriptor instead.
func (*CustomPattern) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CustomPattern) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CustomPattern) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// QueryParameterBinding describes a query parameter to request message binding.
type QueryParameterBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// selector is a dot separated path to the request message's field.
	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// name is the name of the HTTP query parameter that will be used.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// ignore avoids reading this query parameter altogether (default: false).
	Ignore bool `protobuf:"varint,3,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *QueryParameterBinding) Reset() {
	*x = QueryParameterBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParameterBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameterBinding) ProtoMessage() {}

func (x *QueryParameterBinding) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParameterBinding.ProtoReflect.Descriptor instead.
func (*QueryParameterBinding) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *QueryParameterBinding) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *QueryParameterBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryParameterBinding) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

// StreamConfig sets the behavior of the HTTP server for gRPC streaming methods.
type StreamConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// disable_websockets indicates whether or not websockets are allowed for this method.
	// client must still ask for a connection upgrade.
	DisableWebsockets bool `protobuf:"varint,1,opt,name=disable_websockets,json=disableWebsockets,proto3" json:"disable_websockets,omitempty"`
	// disable_sse indicates whether or not server-sent events are allowed.
	//
	// see: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
	//
	// SSE is only used when Accept-Type from the request includes MIME type text/event-stream.
	DisableSse bool `protobuf:"varint,2,opt,name=disable_sse,json=disableSse,proto3" json:"disable_sse,omitempty"`
	// disable_chunked indicates whether or not chunked transfer encoding is allowed.
	//
	// NOTE: chunked transfer encoding is disabled in HTTP/2 so this option will only be available if request
	// is HTTP/1.
	DisableChunkedTransfer bool `protobuf:"varint,3,opt,name=disable_chunked_transfer,json=disableChunkedTransfer,proto3" json:"disable_chunked_transfer,omitempty"`
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshapi_gateway_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_meshapi_gateway_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_meshapi_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *StreamConfig) GetDisableWebsockets() bool {
	if x != nil {
		return x.DisableWebsockets
	}
	return false
}

func (x *StreamConfig) GetDisableSse() bool {
	if x != nil {
		return x.DisableSse
	}
	return false
}

func (x *StreamConfig) GetDisableChunkedTransfer() bool {
	if x != nil {
		return x.DisableChunkedTransfer
	}
	return false
}

var File_meshapi_gateway_gateway_proto protoreflect.FileDescriptor

var file_meshapi_gateway_gateway_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x22, 0x4d, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x3e, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22,
	0xbd, 0x04, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x38, 0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x48,
	0x00, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x49, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x5b, 0x0a,
	0x13, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x62, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x41, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x12, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x41, 0x0a, 0x1d, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x1a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x22,
	0xce, 0x03, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x03, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x38, 0x0a,
	0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x48, 0x00, 0x52,
	0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x49, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x0b,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x41, 0x0a, 0x1d, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x35,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x22, 0x3b, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x5f, 0x0a,
	0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x22, 0x98,
	0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x2d, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x77, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x18, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x65, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x16, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x72, 0x65, 0x73, 0x74, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshapi_gateway_gateway_proto_rawDescOnce sync.Once
	file_meshapi_gateway_gateway_proto_rawDescData = file_meshapi_gateway_gateway_proto_rawDesc
)

func file_meshapi_gateway_gateway_proto_rawDescGZIP() []byte {
	file_meshapi_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_meshapi_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshapi_gateway_gateway_proto_rawDescData)
	})
	return file_meshapi_gateway_gateway_proto_rawDescData
}

var file_meshapi_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_meshapi_gateway_gateway_proto_goTypes = []interface{}{
	(*GatewaySpec)(nil),               // 0: meshapi.gateway.GatewaySpec
	(*EndpointBinding)(nil),           // 1: meshapi.gateway.EndpointBinding
	(*AdditionalEndpointBinding)(nil), // 2: meshapi.gateway.AdditionalEndpointBinding
	(*CustomPattern)(nil),             // 3: meshapi.gateway.CustomPattern
	(*QueryParameterBinding)(nil),     // 4: meshapi.gateway.QueryParameterBinding
	(*StreamConfig)(nil),              // 5: meshapi.gateway.StreamConfig
}
var file_meshapi_gateway_gateway_proto_depIdxs = []int32{
	1, // 0: meshapi.gateway.GatewaySpec.endpoints:type_name -> meshapi.gateway.EndpointBinding
	3, // 1: meshapi.gateway.EndpointBinding.custom:type_name -> meshapi.gateway.CustomPattern
	4, // 2: meshapi.gateway.EndpointBinding.query_params:type_name -> meshapi.gateway.QueryParameterBinding
	2, // 3: meshapi.gateway.EndpointBinding.additional_bindings:type_name -> meshapi.gateway.AdditionalEndpointBinding
	5, // 4: meshapi.gateway.EndpointBinding.stream:type_name -> meshapi.gateway.StreamConfig
	3, // 5: meshapi.gateway.AdditionalEndpointBinding.custom:type_name -> meshapi.gateway.CustomPattern
	4, // 6: meshapi.gateway.AdditionalEndpointBinding.query_params:type_name -> meshapi.gateway.QueryParameterBinding
	5, // 7: meshapi.gateway.AdditionalEndpointBinding.stream:type_name -> meshapi.gateway.StreamConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_meshapi_gateway_gateway_proto_init() }
func file_meshapi_gateway_gateway_proto_init() {
	if File_meshapi_gateway_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshapi_gateway_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewaySpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdditionalEndpointBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomPattern); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParameterBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshapi_gateway_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meshapi_gateway_gateway_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*EndpointBinding_Get)(nil),
		(*EndpointBinding_Put)(nil),
		(*EndpointBinding_Post)(nil),
		(*EndpointBinding_Delete)(nil),
		(*EndpointBinding_Patch)(nil),
		(*EndpointBinding_Custom)(nil),
	}
	file_meshapi_gateway_gateway_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AdditionalEndpointBinding_Get)(nil),
		(*AdditionalEndpointBinding_Put)(nil),
		(*AdditionalEndpointBinding_Post)(nil),
		(*AdditionalEndpointBinding_Delete)(nil),
		(*AdditionalEndpointBinding_Patch)(nil),
		(*AdditionalEndpointBinding_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshapi_gateway_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshapi_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_meshapi_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_meshapi_gateway_gateway_proto_msgTypes,
	}.Build()
	File_meshapi_gateway_gateway_proto = out.File
	file_meshapi_gateway_gateway_proto_rawDesc = nil
	file_meshapi_gateway_gateway_proto_goTypes = nil
	file_meshapi_gateway_gateway_proto_depIdxs = nil
}
