name: Publish docs via GitHub Pages
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.MKDOCS }}
          CONFIG_FILE: mkdocs.yml
