name: Release using goreleaser
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package Proto Files
        run: 'cd api && tar -czvf ../grpc_api_gateway_proto.tar.gz meshapi/**'

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: '~> v1'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.MKDOCS }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: grpc-api-gateway
          path: dist/*
        env:
          AUR_KEY: ${{ secrets. AUR_KEY }}
